package jdlgc.Ejercicio9;

// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Keys;
import java.util.*;

public class Test10Test {
	
  private WebDriver driver;
  JavascriptExecutor js;
  
  @Before
  public void setUp() {
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    new HashMap<String, Object>();
  }
  
  @After
  public void tearDown() {
    driver.quit();
  }
  
  @Test
  public void test10() {
    driver.get("https://www.saucedemo.com/");
    driver.manage().window().setSize(new Dimension(1512, 944));
    driver.findElement(By.cssSelector("*[data-test=\"username\"]")).sendKeys("standard_user");
    driver.findElement(By.cssSelector("*[data-test=\"password\"]")).sendKeys("secret_sauce");
    driver.findElement(By.cssSelector("*[data-test=\"password\"]")).sendKeys(Keys.ENTER);
    {
      WebElement dropdown = driver.findElement(By.cssSelector("*[data-test=\"product_sort_container\"]"));
      dropdown.findElement(By.cssSelector("*[value='lohi']")).click();
    }
    assertEquals(driver.findElement(By.cssSelector(".active_option")).getText(), is("PRICE (LOW TO HIGH)"));
  }
  
}
