package jdlgc.Ejercicio9;

// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Keys;
import java.util.*;

public class Test9Test {
	
  private WebDriver driver;
  JavascriptExecutor js;
  
  @Before
  public void setUp() {
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    new HashMap<String, Object>();
  }
  
  @After
  public void tearDown() {
    driver.quit();
  }
  
  @Test
  public void test9() {
    driver.get("https://www.saucedemo.com/");
    driver.manage().window().setSize(new Dimension(1512, 944));
    driver.findElement(By.cssSelector("*[data-test=\"username\"]")).sendKeys("standard_user");
    driver.findElement(By.cssSelector("*[data-test=\"password\"]")).sendKeys("secret_sauce");
    driver.findElement(By.cssSelector("*[data-test=\"password\"]")).sendKeys(Keys.ENTER);
    driver.findElement(By.cssSelector("#item_4_title_link > .inventory_item_name")).click();
    driver.findElement(By.cssSelector("*[data-test=\"add-to-cart-sauce-labs-backpack\"]")).click();
    driver.findElement(By.linkText("1")).click();
    {
      List<WebElement> elements = driver.findElements(By.cssSelector("*[data-test=\"remove-sauce-labs-backpack\"]"));
      assert(elements.size() > 0);
    }
    driver.findElement(By.cssSelector("*[data-test=\"continue-shopping\"]")).click();
    driver.findElement(By.cssSelector("*[data-test=\"add-to-cart-sauce-labs-bolt-t-shirt\"]")).click();
    driver.findElement(By.linkText("2")).click();
    {
      List<WebElement> elements = driver.findElements(By.cssSelector("*[data-test=\"remove-sauce-labs-backpack\"]"));
      assert(elements.size() > 0);
    }
    {
      List<WebElement> elements = driver.findElements(By.cssSelector("*[data-test=\"remove-sauce-labs-bolt-t-shirt\"]"));
      assert(elements.size() > 0);
    }
    driver.findElement(By.cssSelector("*[data-test=\"checkout\"]")).click();
    assertEquals(driver.findElement(By.cssSelector(".title")).getText(), is("CHECKOUT: YOUR INFORMATION"));
    driver.findElement(By.cssSelector("*[data-test=\"firstName\"]")).click();
    driver.findElement(By.cssSelector("*[data-test=\"firstName\"]")).sendKeys("Jorge");
    driver.findElement(By.cssSelector("*[data-test=\"lastName\"]")).sendKeys("Cordobés Delgado");
    driver.findElement(By.cssSelector("*[data-test=\"postalCode\"]")).sendKeys("28024");
    driver.findElement(By.cssSelector("*[data-test=\"continue\"]")).click();
    assertEquals(driver.findElement(By.cssSelector(".summary_subtotal_label")).getText(), is("Item total: $45.98"));
    driver.findElement(By.cssSelector("*[data-test=\"finish\"]")).click();
    assertEquals(driver.findElement(By.cssSelector(".complete-header")).getText(), is("THANK YOU FOR YOUR ORDER"));
    driver.findElement(By.cssSelector("*[data-test=\"back-to-products\"]")).click();
    driver.findElement(By.cssSelector(".shopping_cart_link")).click();
    {
      List<WebElement> elements = driver.findElements(By.cssSelector("*[data-test=\"remove-sauce-labs-backpack\"]"));
      assert(elements.size() == 0);
    }
    {
      List<WebElement> elements = driver.findElements(By.cssSelector("*[data-test=\"remove-sauce-labs-bolt-t-shirt\"]"));
      assert(elements.size() == 0);
    }
  }
  
}
